image: node:latest
before_script:
  - npm install
  - npm run prepare
cache:
  key: "$CI_PROJECT_PATH/$CI_BUILD_REF_NAME/$NODE_VERSION"
  paths:
  - node_modules/
test_all:
  script:
   - npm run test
